### ISSUE TITLE
Approve clarification of gain_setting in NXdetector

### ISSUE THREAD

**Issue by benajamin** [nexusformat/NIAC#100]
The proposal is to approve pull request https://github.com/nexusformat/definitions/pull/896 to allow free choice of values in the `gain_setting` field of `NXdetector`.

Current NXDL:
```
 <doc>The gain setting of the detector. This influences background etc.</doc>
    <enumeration>
      <item value="high"/>
      <item value="standard"/>
      <item value="fast"/>
      <item value="auto"/>
    </enumeration>
 </doc>
``` 
Proposed NXDL:
```
  <doc>
      The gain setting of the detector. This is a detector-specific value
      meant to document the gain setting of the detector during data
      collection, for detectors with multiple available gain settings.
  </doc>
```

**Comment by prjemian** [comment]
We should continue to list (now in the documentation if this is approved) the expected values.

**Comment by benajamin** [comment]
Consensus is that this would be much improved by including a list of recommended strings. We would like to consider a revision in the near future.

**Comment by phyy-nx** [comment]
Ready for further review after addressing feedback from Spring NIAC 2022

**Comment by benajamin** [comment]
The approved changes have been implemented in https://github.com/nexusformat/definitions/pull/896
