### ISSUE TITLE
Base Class and Application Definition development questions

### ISSUE THREAD

**Issue by sanbrock** [nexusformat/NIAC#107]
- [x] nexusformat/definitions#1066 --> https://github.com/nexusformat/definitions/issues/1056
- [x] nexusformat/NIAC#121
- [x] nexusformat/NIAC#120
- [x] nexusformat/NIAC#122
- [x] nexusformat/definitions#1057
- [x] nexusformat/definitions#1058
Proposal:
- enum list are inherited
- enum list are overriding inherited lists
- inheritance comes from the direct super class
- [x] nexusformat/definitions#1059
E.g. if NXdetector_module/data_origin<doc> is overwritten by  NXdetector/detector_module/data_origin, and then  NXmyappdef:/detector (NXdetector)/detector_module(NXdetector_module) is used will it inherit from NXdetector_module or from NXdetector/NXdetector_module?
Proposal:
- documentation shall not override, but rather extend and/or specialise
- [x] support for derived unit types (NX_COMPOSITE) -- https://github.com/nexusformat/definitions/issues/1067
Proposal:
- unidata composition shall be supported
- unidata 'unknown' could be used if derivation has not actually been performed
- [x] nexusformat/definitions#1064
- [x] Similarly, if we specify multiple optional fields/groups, how can we enforce that at least one of them shall be present
- [x] nexusformat/definitions#1065
- [x] nexusformat/NIAC#124
- [x] nexusformat/definitions#1063
- [x] nexusformat/NIAC#135
- [x] similar question for application definitions, although NXxkappa is already extending NXxbase
- [x] nexusformat/NIAC#126
- [x] nexusformat/definitions#1046

**Comment by prjemian** [comment]
Issues have been created from all discussion points.  Closing this issue.
