### ISSUE TITLE
Reserve field prefix `DECTRIS_`

### ISSUE THREAD

**Issue by benajamin** [nexusformat/NIAC#110]
The proposal is to reserve the name prefix `DECTRIS_` for use by Dectris AG. This simply adds to the existing list of [reserved prefixes](https://manual.nexusformat.org/datarules.html?#reserved-prefixes).

**Comment by benajamin** [comment]
The NIAC would like to provide a location to store documentation associated with prefixed objects in NeXus files.

**Comment by prjemian** [comment]
See pull request https://github.com/nexusformat/definitions/pull/1036
