### ISSUE TITLE
Deprecate incr attribute in dimensionsType

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/NIAC#112]
Reading the description for [incr](https://manual.nexusformat.org/nxdl_desc.html#incr), it seems that it was accidentally left undeprecated in 2016 when the ref and refindex tags were deprecated for https://github.com/nexusformat/definitions/issues/330.

**Comment by PeterC-DLS** [comment]
Added issue to agenda for NIAC on nexusformat/NIAC#112

**Comment by benajamin** [comment]
We discussed the issue and feel that incr not being deprecated together with ref and refindex should be considered a bug. We will need a pull request to make the change to the documentation.
