### ISSUE TITLE
Protect main branch of repos

### ISSUE THREAD

**Issue by PeterC-DLS** [nexusformat/NIAC#113]
Seems to be a sensible and standard thing to do

**Comment by benajamin** [comment]
Can you please describe what this means in some detail? I assume you mean to only allow a select group of github accounts to merge pull requests to main - is that correct? Would the authorised group be the [project owners](https://github.com/orgs/nexusformat/people?query=role%3Aowner)?

**Comment by PeterC-DLS** [comment]
No, I mean this [about-protected-branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches). So requirements such as CI checks can pass before a merge.

**Comment by prjemian** [comment]
This is a good protection that means any change to the main branch will come from a branch that passes testing.

**Comment by prjemian** [comment]
It also means that trivial changes (such as typos in the documentation) MUST go through a branch/fork & pull request process.

**Comment by benajamin** [comment]
Proposal is to authorise Peter Change to protect the nexusformat repository main branches.

**Comment by PeterC-DLS** [comment]
Ok, I have protected the definitions repo's main branch so that
1. a pull request is required before merging
2. that PR needs 1 approval before merging
3. status checks required to pass
4. conversations on code in PR  need resolving
5. include admins in protection
6. not require linear history (may want to change in future)
