### ISSUE TITLE
Review NXdirecttof

### ISSUE THREAD

**Issue by mkoennecke** [nexusformat/NIAC#12]
After discussion with jkrueger1 at FRM-2 there were the following change requests for NXdirecttof.
This regarding applying NXdirectof to the FRM-2 instrument TOFTOF. 
- TOFTOF has no fermi chopper but disk choppers only. Suggestion: allow both
- NXmonitor: they do not have a time-of-flight monitor, make data, time_of_flight optional 
- Jens Krueger will add requests for additional fields

**Comment by zjttoefs** [comment]
I think a pull request has been merged to address these changes.
