### ISSUE TITLE
References inside NeXus uses links. Can we use/introduce something like PID?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/NIAC#122]

**Comment by prjemian** [comment]
Suggest this be opened as a [new issue](https://github.com/nexusformat/definitions/issues/new) for discussion in the definitions repository.  In that new issue, add this URL (`https://github.com/nexusformat/NIAC/issues/122`) to link back to this NIAC discussion.

**Comment by prjemian** [comment]
Once the issue is opened, this NIAC issue can be closed.

**Comment by benajamin** [comment]
New issue has been opened.
