### ISSUE TITLE
can an application definition define multiple entries?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/NIAC#126]

**Comment by prjemian** [comment]
No.  An application definition is a group under `NXentry` or a peer.

**Comment by benajamin** [comment]
The consensus seems to be that it is not technically possible for an application definition to state any requirements about the use of `NXentry` groups to structure the data. However, you can advise the community to structure data using `NXentry` groups. For `NXstxm`, I published an [article](https://doi.org/10.1063/1.4937536) that stated the following:

> NeXus provides NXentry as a way of allowing multiple measurements in the one file, if there is some reason for
> grouping them together. A set of measurements that are made in parallel or form a consecutive set, for example,
> could be written into separate NXentrys within the same HDF5 file. Pixelator, and other STXM control programs,
> allow a user to measure multiple spatial regions in parallel such that the instrument will execute scans of each
> regions in sequence using the first photon energy before repeating the same set of spatial regions using the next
> photon energy and so on for each requested photon energy. In this case, a conforming NXstxm file will contain one
> NXentry group for each spatial region such that the contents of each NXentry group is identical to the case where
> that spatial region alone had been scanned. The example given in Fig. 1 scans a single spatial region and so contains
> a single NXentry group named ‘entry1’.

**Comment by benajamin** [comment]
The use of `NXentry` for storing multiple measurements in a single file is mentioned in the manual in the [Using an Application Definition](https://manual.nexusformat.org/applying-nexus.html#using-an-application-definition) section. I think this might be an appropriate place to explicitly state that application definitions have no power to enforce usage of NXentry.
