### ISSUE TITLE
Increase opportunity for voting

### ISSUE THREAD

**Issue by woutdenolf** [nexusformat/NIAC#143]
http://www.nexusformat.org/NIAC.html

> Voting outside of the biennial NIAC meetings can take two forms. Firstly, memberships can be approved by email ballot. All other issues require a teleconference for interactive discussion that is attended by at least 2/3 of the NIAC. Votes may be cast at the teleconference, as well as during the following week in order to allow NIAC members not attending the teleconference to add their vote to the tally. The opening of the voting period must be advertised through the NIAC mailing list. At the close of the 1-week voting period, NIAC members not responding are counted as abstained and the NIAC decision follows the voting category (usually “for” and “against”) with the highest number of valid votes.

We can use github polls for this part:

> Votes may be cast  ... during the following week

* Enable github discussions for the https://github.com/nexusformat/NIAC/ project or perhaps the organization https://github.com/nexusformat/ (https://docs.github.com/en/discussions/quickstart)
* Open a poll: https://docs.github.com/en/discussions/quickstart#creating-a-new-poll
* Poll options are: approve, reject, abstain, more information needed
* Resolve the poll as described in the constitution (close after 1 week, non-voters automatically abstain)

We may want to change the constitution to increase voting opportunity:

* Extend the 1 week voting period. Perhaps 2 weeks?
* Starting a vote at a teleconference does not need 2/3 NIAC attendees but when resolving the vote, a decision can only be made when 2/3 NIAC members cast a vote (no automatic abstaining)?

**Comment by woutdenolf** [comment]
Ping @phyy-nx @sanbrock

**Comment by woutdenolf** [comment]
I have a question on this part of the constitution:

> At the close of the 1-week voting period ... NIAC decision follows the voting category (usually “for” and “against”) with the highest number of valid votes.

Currently we have 19 members so 2/3 is 13 members.

1. Suppose the voting period ends and only 12 NIAC members cast a vote: the proposal gets rejected by default?
2. Suppose the voting period ends and 13 NIAC members cast a vote (i.e. quorum reached), 7 approve and 6 reject: the proposal gets accepted?

**Comment by woutdenolf** [comment]
All described above falls under "Voting outside of the biennial NIAC meetings"

> Topics voted on at the biennial NIAC meetings will require a simple majority unless specifically challenged by a committee member.

So if there is a "biennial NIAC meeting" (whatever that is) with 5 NIAC members and there is a vote with 3 approved, the proposal gets accepted?

**Comment by phyy-nx** [comment]
Hi @woutdenolf, your questions are the same ones I have.  At least I can answer the one about biennial NIAC meetings.  We've had full NIAC meetings consistently since 2010 at least every 2 years, usually in person and tied to NOBUGS, as documented here: https://www.nexusformat.org/NIAC.html.  These are the main meetings where substantive changes are allowed, and voting is by majority of those present.

NeXus is moving faster these days, and so as part of the 2023 Code Camp, we discussed the proposals and questions @woutdenolf outlined above, mainly allowing NIAC votes for substantive changes to be started at telcos, announced by email, and documented as emojis on specific github pull requests.  I am hoping for quorum in our July 2023 Telco where I'll be presenting changes to the constitution along these lines.

Note, that while I have specific pressure from companies to get some changes through the NIAC approval process,  I'm keen that it's done properly, with peer review and discussion.  That said, I don't think I can wait until [2024](https://www.nobugsconference.org/).  @nexusformat/developers I'd greatly appreciate your attention to @sanbrock's upcoming telco scheduling email for July!

Thanks all!

**Comment by phyy-nx** [comment]
Bump!  Telco tomorrow :)

(or today depending on your time zone)

**Comment by phyy-nx** [comment]
Hi all, during the July 24th we discussed voting.  Here is a proposal to loosen the current restrictions.  Existing text has been modified as follows:

> Voting outside of the biennial NIAC meetings can take two forms. Firstly, memberships can be approved by email ballot. All other issues require a ~~teleconference for interactive discussion~~ **vote using a poll** that is ~~attended~~ **completed** by at least 2/3 of the NIAC. Votes may be cast ~~at the teleconference, as well as~~ during the following **two** week**s** in order to allow NIAC members **time** ~~not attending the teleconference~~ to add their vote to the tally. The opening of the voting period must be advertised through the NIAC mailing list. At the close of the ~~1~~**2**-week voting period, NIAC members not responding are counted as abstained and the NIAC decision follows the voting category (usually “for” and “against”) with the highest number of valid votes.

This generated a lot of discussion, and I've summarized feedback and other suggestions here for other possible solutions:
- Subdivide NIAC into voting vs. observing members
- Allow NIAC members to nominate a proxy to vote for them when they are not available. Nominating a proxy makes them count towards quorum
- Allow automatic suspension of membership, where they no longer count against quorum after a certain time of lapsed participation.  Participation could include email, GitHub discussion, and participation in Telcos.  Maybe 8 months?  Again, this is to help getting quorum
- Have we outgrown being a standards body managed by consensus?  Are we more of an open source community? If so, we need to relax quorum requirements.
- Need better onboarding for new NIAC members to help learn about NeXus enough that they feel comfortable participating
- Need to be clear about our releases, so companies know what they are implementing to.
- (aside) We need to due a new release.  End of August?
- It seems reasonable that PRs to application definitions need less strict scrutiny, perhaps merely approval from 1-2 of the contributors listed in the application definition, assuming they are still active.
- But it also seems reasonable that changes to base classes need more community involvement.  Maybe even a voting procedure like what is listed above.
- Change to annual meeting not tied to NOBUGs.
- Should we include voting on releases as a confidence measure, in the case where we adopt application definitions with looser scrutiny

Regardless of all the above feedback, my opinion is that my above proposal is the minimum required to get us to a point where we can effectively introduce change to NeXus.  I could have pushed for a broader change incorporating some of the above comments, but I thought starting small is more feasible.

Please attend the August 14th Telco!

**Comment by phyy-nx** [comment]
Hi, I received revisions from @yayahjb and @benajamin that I've merged into the following alternative:

> Voting outside of the biennial NIAC meetings can take two forms. Firstly, memberships can be approved by email ballot. All other issues require a vote that receives responses from at least 2/3 of the NIAC during the following two week voting period. The opening of the voting period must be advertised through the NIAC mailing list. At the close of the voting period, NIAC members who have not responded are counted as having abstained.  Whether the issue involved is membership or any other issue, the NIAC decision shall be determined by whatever outcome receives a plurality of the votes that are not abstentions, i.e. the outcome which receives more votes than any other outcome other than abstention, even if the chosen outcome does not receive an absolute majority of the votes.

**Comment by sanbrock** [comment]
During the Telco, we have revised the paragraph and are proposing the following:

Voting outside of the biennial NIAC meetings can take two forms. Firstly, memberships can be approved by email ballot. All other issues require a vote that receives responses from at least 2/3 of the NIAC during the following two week voting period. The opening of the voting period must be advertised through the NIAC mailing list. At the close of the voting period, NIAC members who have not responded have abstained (and are not counted towards the 2/3 requirement). Whether the issue involved is membership or any other issue, the NIAC decision shall be determined by whatever outcome receives a plurality of the votes that are not abstentions, i.e. the outcome which receives more votes than any other outcome other than abstention, even if the chosen outcome does not receive an absolute majority of the votes.

**Comment by yayahjb** [comment]
Aye -- Herbert

**Comment by phyy-nx** [comment]
Hi all, we will vote on the text that @sanbrock posted [above](https://github.com/nexusformat/NIAC/issues/143#issuecomment-1677583114) that was the result of discussion from today's Telco when we next have quorum.

For completeness I'll also note here that we discussed the time limit of 2 weeks and considered a) 4 weeks instead but the consensus on the call was that this was too long and b) some kind of automatic procedure where a vote was 'called' if 51% of the NIAC voted yes (absolute majority) and at least 2/3rds responded in total.  We decided this was too cumbersome for now and left it out.

Thanks all.

**Comment by phyy-nx** [comment]
Telco Nov 21 2023 was attended by 15 members, enabling us to start a vote on this constitutional change:

> Voting outside of the biennial NIAC meetings can take two forms. Firstly, memberships can be approved by email ballot. All other issues require a vote that receives responses from at least 2/3 of the NIAC during the following two week voting period. The opening of the voting period must be advertised through the NIAC mailing list. At the close of the voting period, NIAC members who have not responded have abstained (and are not counted towards the 2/3 requirement). Whether the issue involved is membership or any other issue, the NIAC decision shall be determined by whatever outcome receives the most votes that are not abstentions, i.e. the outcome which receives more votes than any other outcome other than abstention, even if the chosen outcome does not receive an absolute majority of the votes.

Please vote with an emoji on this comment.  Options include thumbs up for yes, thumbs down for no, and anything else to abstain.  Thank you.

**Comment by ounsy** [comment]
Ok!

**Comment by phyy-nx** [comment]
The motion has passed with 18 yes votes.  Thank you all for participating.
