### ISSUE TITLE
What is the decision on variable length strings?

### ISSUE THREAD

**Issue by prjemian** [nexusformat/NIAC#23]
Regarding #10, there is no record of a final NIAC vote on whether to accept variable length strings.

Question came up today in the context of a file written by Diamond Light Source with a link (target attribute written as variable length string) that was not recognized as a NeXus link by NeXpy.

**Comment by zjttoefs** [comment]
http://www.nexusformat.org/NIAC2016Minutes.html


## Variable length strings
Short discussion on fixed versus variable length strings.

We accept both variable and fixed length strings, readers have to support both, 11 yes, 1 no
