### ISSUE TITLE
NX_CHAR

### ISSUE THREAD

**Issue by vasole** [nexusformat/NIAC#24]
I have posted the message below to nexus@nexusformat.org but apparently the message did not get through or got stopped somewhere.

Dear colleagues,

I think there is a problem with the BasicWriter.py example found at:

http://download.nexusformat.org/sphinx/examples/h5py/index.html

Unfortunately, that example is targeting Python 2.x and that can lead to
misunderstandings.

If I read the documentation, NX_CHAR fields should be UTF-8 encoded strings.

Running the example, all the attributes are read as bytes and not as
UTF-8 encoded strings when read under Python 3.

The worst thing is that if the example is run under Python 3 (just by
adding the missing parenthesis to the print statements), the generated
file is different because indeed, strings are strings and not bytes
without any encoding.

Please, clarify is NX_CHAR fields should correspond to UTF-8 encoded
strings or to byte strings.

The example should be fixed and all the attribute strings should have a
lower case U character prepended in order to:

- Comply with the documentation
- Generate same output under Python2 and Python3
- Generate same input under Python2 and Python3

Best regards,

Armando

**Comment by prjemian** [comment]
Indeed, that was purely py2.7

**Comment by vasole** [comment]
Yes, but even under python 2.7 is not compliant with NX_CHAR being a UTF-8 string. Therefore I am asking for clarification.

The code is missing the conversion to unicode on all the attributes either by prepending a U or by explicitly writing unicode(text, "utf-8"). The former is preferable as "unicode" does not exists unde Python 3.

**Comment by prjemian** [comment]
I'll fix that code per your remarks.  Thanks.

**Comment by prjemian** [comment]
created https://github.com/nexusformat/definitions/issues/594 for the unicode changes

**Comment by prjemian** [comment]
created https://github.com/nexusformat/definitions/issues/595 for the Python3 enhancement
