### ISSUE TITLE
[NIAC 2018 Proposals] NXdata@auxiliary_signals (It was How to specify multiple signals?)

### ISSUE THREAD

**Issue by vasole** [nexusformat/NIAC#25]
**Typical use cases:**

- Plotting several counters at scanned positions.
- Fitting raw data and willing to generate a plot with the raw data and the fitted data
- Elemental mapping where a map is generated for each element
....

The combination of multiple signals with the use of NXprocess would solve many provenance issues. 

**Proposed Implementation**

In the past, everything was ready for the implementation via allowing to have multiple datasets with the signal attribute in an NXdata group and by playing with attribute values "1", "2", "3". That approach is not any longer possible.

<del>- Proposal 1: Allow signal to be an array of string with the first element of the array to be treated as it is now the case with single signals.</del>
<del>- Proposal 2: Define a signals attribute being an array of strings with the first element of the array to be treated as it is now the case with single signals.</del>
- Proposal 3: Define a new set of groups  NXplot1d, NXplot2d, NXplot3d, ... allowing so.
- Proposal 4: Allow a new NXdata attribute named auxiliary_signals containing the additional datasets that can be plotted alongside with the signal. The proposal is so flexible that auxiliary_axes could be considered for the future but for the main goal of this issue is not needed.

**Comment by rayosborn** [comment]
It might be worth giving a concrete example here to see what is really needed. Pete Jemian has written a nice SPEC importer, [spec2nexus](http://spec2nexus.readthedocs.io/), which creates a single NXentry for each scan containing a single NXdata group. Here are the contents (with a few attributes removed):
```
data:NXdata
  @axes = 'Two_Theta'
  @signal = 'NaI'
  Epoch = float64(26)
  H = float64(26)
  K = float64(26)
  L = float64(26)
  NaI = float64(26)
  Ring = float64(26)
  Seconds = float64(26)
  Two_Theta = float64(26)
  detector = float64(26)
  ic0 = float64(26)
  ic1 = float64(26)
  ic2 = float64(26)
  ic3 = float64(26)
```
In other words, every SPEC column is included in the NXdata group, but only one is selected to be the default signal and one to be the default axis. In [NeXpy](http://nexpy.github.io/nexpy/), if you double-click on the NXdata group, it will plot with the default signal vs the default axis, but you can also double-click on any of the NXdata fields to plot it against any of the remaining fields, as long as the dimension sizes match. 

So I think it may be overly complicated to have to specify which of the above fields refers to a signal and which to an axis - for example, you might want to plot two signals against each other. 

To summarize - in my view, it is the role of the NeXus standard to provide a way to offer a default plot for each NXdata group, but I don't think it is necessary for NeXus to then specify all other possible non-default plots. Any program is free to provide that option within the current standard as NeXpy does.

**Comment by vasole** [comment]
On 11/01/2018 15:04, Ray Osborn wrote:
> To summarize - in my view, it is the role of the NeXus standard to
> provide a way to offer a default plot for each NXdata group,

Exact, but to me the default plot for a fit is the raw_data, the used
uncertainties and the fitted curve.

NeXus provides everything for it except the possibility to put the
auxiliary curve.


> but I don't think it is necessary for NeXus to then specify all other
> possible non-default plots.

Nobody is asking for it.

> Any program is free to provide that option within the current standard
> as NeXpy does. 

PyMca does it too, so that is not the problem. However, consider the
marvellous opportunity NeXus offers to provide the output of a fit (or
other treatments), with uncertainties, axis labels, and fitted curve at
the cost of defining two group attributes.

If NIAC tells me that Peter Chang's solution is not going to be
considered at all, it is fine with me too. We'll implement those two
attributes at our side and they will not conflict with any other
implementation.

**Comment by rayosborn** [comment]
Within NeXpy, I have also had to address the issue of how to store fits to the data, but I don't think  that adding an auxiliary attribute solves the problem. For example, I might want to add the individual functions that make up a fit, e.g., Gaussian + Linear background. When you save a fit in NeXpy, it creates a NXsubentry that stores multiple data sets corresponding to the data, total fit, functions making up the fit and their parameters, and other output from the fit. 

I can see that there is an argument to make this an extended definition of an NXprocess group, but I think there is too much information to be included in a single NXdata group. 
```
x_fit:NXsubentry
  Linear:NXdata
    @axes = 'x'
    @signal = 'model'
    model = float64(1001)
    parameters:NXparameters
      Constant = -212.813
      Slope = -0.00592065
    title = 'Fit Results'
    x = float64(1001)
  PDFdecay:NXdata
    @axes = ['x']
    @signal = 'model'
    model = float64(1001)
    parameters:NXparameters
      Amplitude = 11344.648855910262
      Sigma = 67.066
      Xi = 141.2440890911708
    x = float64(1001)
  data:NXdata
    @axes = 'x'
    @signal = 'smooth_fft'
    smooth_fft = float64(19)
    x = float64(19)
  fit:NXdata
    @axes = ['x']
    @signal = 'model'    model = float64(1001)
    title = 'Fit Results'
    x = float64(1001)
  statistics:NXparameters
    chisq = 881389.5351794838
    ier = 1
    lmdif_message = 'Both actual and predicted relative reductions in the sum...'
    message = 'Fit succeeded.'
    nfev = 18
    redchi = 51846.44324585199
  title = 'Fit Results'
```

**Comment by vasole** [comment]
Updated the issue to add proposal 4 that is by far better than proposals 1 and 2 that in my opinion do not offer any advantage in comparison.

- Proposal 4: Based on Peter Chang's suggestion in the mailing list. Allow a new NXdata attribute named auxiliary_signals containing the additional datasets that can be plotted alongside with the signal. The proposal is so flexible that auxiliary_axes could be considered for the future but for the main goal of this issue is not needed.

**Comment by PeterC-DLS** [comment]
Regarding proposal 4, to reuse existing parsing code, the datasets named in the `auxiliary_signals` attribute could each have their own `AUXDATA_axes` attributes (rather than the proposed `auxiliary_axes` attribute).

There are a couple of problems:
-  extra `_indices` attributes that are not referenced by `AUXDATA_axes` attributes would complicate the deduction of which alternative axes pertain to which signal (auxiliary or otherwise);
- variable (or axis) name collisions (could overcome with the `long_name` attribute)

**Comment by prjemian** [comment]
@PeterC-DLS : NeXus has moved away from adding such attributes to the fields since the attribute will appear any place that field is referenced.  When a field is linked into multiple groups, the field attribute could be problematic in one or more of the other groups.  It seems more appropriate to consider this as an attribute of the group since it is the group that is assembling that fields to represent as a simple plot.

**Comment by PeterC-DLS** [comment]
@prjemian I did mean applying the `AUXDATA_axes` to the enclosing group. `AUXDATA` is the placeholder for whatever a particular auxiliary dataset is called.

**Comment by mkoennecke** [comment]
The NIAC accepted in 2018 with all in favor to introduce additional group level attributes auxiliary_signals which contains an array of strings holding the names of additional signals to be plotted with the signal.
