### ISSUE TITLE
[NIAC 2018 Proposals] Missing NXdata indications about plot type (linear, semilogx, semilogy, loglog ...)

### ISSUE THREAD

**Issue by vasole** [nexusformat/NIAC#29]
Missing a way to specify how the axes are to be displayed.

Adding additional qualifiers would not break any existing code while it would allow to see the data the way expected by the users.

Using predefined plot types could be one way:

NXdata@signal="I"
NXdata@axes=["q"]
NXdata@plot_type="semilogy"

but that is not generic enough, while something more generic might not be acceptable:

NXdata@signal="I"
NXdata@axes=["q"]
NXdata@plot_type=["linear", "logarithmic"] (list of representations to be associated to each of the axes with the last one to be associated to the signal)

**Any proposal allowing to solve that problem is welcome.**

**Comment by PeterC-DLS** [comment]
I suggest this new attribute could be named axis_scale_type (to not be specialized to just 1-dimensional plots).

However, allowing a prescription for how data should be plotted seems like opening a pandora's box - more attributes will be needed to allow a red dash-dotted line. If it comes to that then a RGB dataset of the desired plot would satisfy any exacting specification!

In this case, would it not be better just to write the logged datasets?

**Comment by vasole** [comment]
I like the name proposed. I avoided to mention scale in the opening post in order not to confuse with scales in the sense of transformations.

In your line, to make sure is extendable to other plots, like images that can be represented via logarithmic or linear colormaps, one might need signal_scale_type

The advantage of adding those attributes is that no code is broken while functionality is added.

To write the modified data I find it counterproductive. The data are what they are and they should be separated from their representation because we would end up having two write the data twice (one way to use them and one to visualize them).

**Comment by vasole** [comment]
NIAC 2018 decided NeXus would just say what was to be plotted without entering in how.
