### ISSUE TITLE
Discuss relative virtues of "interfaces" versus "features"

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/NIAC#3]
Relates to the research project: https://github.com/nexusformat/definitions/issues/382

**Comment by mkoennecke** [comment]
[NXinterfaces.pdf](https://github.com/nexusformat/NIAC/files/365968/NXinterfaces.pdf)

I added a pdf which contains only the section of the NeXus manual documenting base classes with  NeXus interfaces for your review. Please note the disclaimer in the introduction of the document.

**Comment by zjttoefs** [comment]
To be discussed at the code camp

**Comment by mkoennecke** [comment]
In pushed the document now into the NIAC repository

**Comment by zjttoefs** [comment]
People are curious what will be the best option in the future. Maybe we need to discuss again.

**Comment by mkoennecke** [comment]
NIAC 2018 decisions:

Interfaces are to be buried as they add more complexity then it is worth. But we look at the interfaces documentation for help in improving the base class documentation.

Application definitions stay in

The feature attribute is official. Features will be made available through the NeXus WWW-site as technical preview.
