### ISSUE TITLE
[NIAC 2018 Discussion] - Input from the McStas team

### ISSUE THREAD

**Issue by willend** [nexusformat/NIAC#33]
Hi NIAC, here is a little **input from McStas for the NOBUGS 2018 satellite**:

- **McStas have been early adopters**, NeXus in the McStas code tree since ~ 2003, using the napi.h c-API. It was therefore not so nice to hear that NeXus will eventually deprecate this interface, even though our napi use is relatively basic and can likely be replaced by direct calls to HDF5.

- **Our code is very platform independent** and is deployed to both Windows machines, Mac’s and Linux’es by our users. It is therefore very important that good deployment strategies for the NeXus libs exist for all of those platforms, ideally by availability of installer packages.

- Specifically: The **latest available macOS installer** on GitHub is for **NeXus 4.3.0 and built for 32bit** systems...! (https://github.com/nexusformat/code/releases/download/4.3.0/NeXus-4.3.0.dmg)

- -> It is **beyond the average capability** of a McStas user to build NeXus locally - and I don’t
feel it should be my task to deploy NeXus with McStas. :-)

- A current use of NeXus in McStas is for the transfer of instrument geometry and event-data to Mantid, including a ‘hack' that generates an XML-based IDF. Any **direct support for Mantid- oriented geometry information in NeXus** will be welcomed, especially if this happens via the availability of e.g. a c-api...

Best,
Peter Willendrup on behalf of the McStas / McXtrace team

**Comment by prjemian** [comment]
Per the [NeXus documentation](https://manual.nexusformat.org/napi.html):

> the decision has been taken to freeze the NAPI. Maintenance is reduced to bug fixes.

It appears that the NAPI is overdue for a bug-fix release, at least.  At the moment, we are building for linux on the CI (jenkins) server.  We need to look into whether or not we are building for other OS.  As Microsoft further [deliberates Linux](https://linux.slashdot.org/story/20/10/11/0225229/what-if-they-replaced-windows-with-microsoft-linux) as an underpinning of Windows, this could impact the builds for Windows.

**Comment by prjemian** [comment]
Note the last NAPI release, 4.4.3, was 2016-09-12 : https://github.com/nexusformat/code/releases

**Comment by stuartcampbell** [comment]
I agree, a bug fix release is something we should do.
