### ISSUE TITLE
[NIAC 2018 Proposals] Attribute to define signal normalization

### ISSUE THREAD

**Issue by rayosborn** [nexusformat/NIAC#34]
It is common for data to be stored as an unnormalized signal with a separate normalization array. This allows multiple data sets to be merged or rebind reliably when the weights are not defined by the uncertainties. It is common in Mantid, where NXdata groups stored within MDHistoWorkspace entries contain a `numevents` array that should be used to normalize the `data` array. The X-ray software CCTW stores signals and weights of individual runs separately before merging them together.

I propose that we add an optional attribute `normalization` to the NXdata class attributes, to accompany a `signal` attribute. When it is present, plotting software should divide the `signal` array by the `normalization` array before plotting or performing other operation on the normalized data. This should be specified at the group level because the arrays are often stored in separate files so placing the attribute on the array itself might not be possible.

**Comment by vasole** [comment]
I will support it provided but you start thinking (if not already done) about how to normalize a dataset by a normalization dataset of different dimension.

Hint: The original dataset (the one to be divided) can have the interpretation attribute set (that is actually a dataset attribute)

**Comment by rayosborn** [comment]
I had assumed the shape of the two arrays had to be the same, but I'm open to alternative views.

**Comment by vasole** [comment]
My point is that one also needs to normalize, for instance, n spectra or n images either to a single scalar or to n scalars. Therefore it is enough that whatever shape the array of spectra has or the array of images has, if they have the interpretation attribute set, we know what can be normalized and what cannot.

If there is no interpretation, then only equal shapes can be used, but in my field (spectroscopy), you have scalar intensity monitors and 1D (interpretation="spectrum") or 2D (interpretation="images") signals. In fact, I rarely have the same dimension for the monitor as for the signal.

**Comment by rayosborn** [comment]
If we only allow this attribute to be applied to the field, rather than a group, then we are unable to use it in our workflow. Specifically, CCTW produces an HDF5 file that contains the signal and weights, and we create external links to those arrays. We cannot add attributes to an external link, so our only option is to add it to the enclosing NXdata group. Insisting that it be a field attribute would make this proposal useless to us.

**Comment by mkoennecke** [comment]
The NIAC decided in 2018 with 9/0/1 for a field DATASETNAME_weights for this. If software encounters the combination of DATSETNAME, DATASETNAME_weights it is supposed to divide DATASETNAME by DATASETNAME_weights
