### ISSUE TITLE
[NIAC Proposals] Attribute to add masks to signals

### ISSUE THREAD

**Issue by rayosborn** [nexusformat/NIAC#35]
I propose that we add an optional string attribute normalization to the NXdata class attributes, to accompany a `signal` attribute. When it is present, the `signal` array should be masked by an integer or boolean array specified by the attribute. Values of 1 in the mask array would correspond to masked data. For example, when read by a Python package, the Numpy array containing the `signal` data could be converted to a `MaskedArray` using the `mask` array. This should be specified at the group level because the mask array could be stored in a separate file so placing the attribute on the array itself might not be possible.

This is functionally similar to #34.

**Comment by vasole** [comment]
On this one I will need to be convinced. My caveats:

- A mask starts to be far from a display operation (purpose of NXdata). 
- It looks too Python specific to me

**Comment by rayosborn** [comment]
Perhaps I shouldn't have given a Python example, but the implementation of the mask would be up to the reading software. The philosophy of how we use NXdata groups should be discussed at the meeting. We use them as data objects, not just display objects.

**Comment by prjemian** [comment]
This proposal is about a field attribute and is not specific to NXdata, nor is it specific to any programming language.

Have you looked at the existing [`pixel_mask`](pixel_mask) in [NXdetector](http://download.nexusformat.org/doc/html/classes/base_classes/NXdetector.html#index-59) and used in [NXmx](download.nexusformat.org/doc/html/classes/applications/NXmx.html#index-25)?  Also, [NXcanSAS](http://download.nexusformat.org/doc/html/classes/applications/NXcanSAS.html#index-17) has a `@mask` attribute to name the mask field.  I believe the `pixel_mask` is already in use by Dectris in the files written from their Eiger detectors.

I propose we adopt this attribute

**Comment by rayosborn** [comment]
We use `pixel_mask` extensively as a 2D mask, which can be broadcast to every frame. However, the `mask` proposed here has the same shape as the `signal`, although I suspect that Numpy also allows mask arrays to be broadcast to a higher-dimensional array. 

I think there is an argument about whether the `mask` attribute should be optional for both fields and NXdata groups, since they might be useful in both contexts. However, as a group attribute, it only makes sense to add it to a NXdata group that has an associated `signal` array defined.

**Comment by vasole** [comment]
I think one can have the mask as an "auxiliary_signal". If an application wants to use in a particular way based on the name, then it is up to the application but at least we are not Python specific and we are not out of context.

**Comment by rayosborn** [comment]
I want to repeat that this proposal is not Python-specific. The concept of masking an array, so that the masked values are not used in, e.g., statistical functions such as averages, can be implemented in any language. It happens that Python has a convenient method of implementing masks, but I don't believe we should reject a proposal because of that. 

The mask cannot be considered an 'auxiliary signal' - it is not an additional array to be plotted along with other signals. It is an array that modifies how the `signal` array is handled.

**Comment by kif** [comment]
Hi Ray,
If you implement the mask, why not implementing a generic function evaluation like

```where(mask, NaN, (data - dark) / flat)```

Either the NIAC decides to do it completely or not at all. The proposition you are suggesting is for me half way and maintains the ambiguity of what is a NXdata.

**Comment by vasole** [comment]
On 24.10.2018 15:55, Ray Osborn wrote:
> 
> The mask cannot be considered an 'auxiliary signal' - it is not an
> additional array to be plotted along with other signals. It is an
> array that modifies how the signal array is handled.
> 

Well, if it is inside an NXdata it can be plotted.

If your NXdata is inside an NXprocess with program equal to your program 
anme, then you can do whatever you want with the data. You know what you 
are expecting and the others can at least infer what those things are.

**Comment by vasole** [comment]
On 24.10.2018 17:31, Ray Osborn wrote:
> 
> People seem to be objecting to this because of some philosophical
> preconceptions about what an NXdata group is for

I'm not arguing about interest.

Documentation stated long ago that the purpose of NXdata was to define a 
plot. (irony mode on) Probably someone can go now and change again the 
documentation (irony mode off)

Because of the unfortunate name, people started to use it as a container 
for other things.

Either we have strict rules, either we drop everything and we use HDF5 
as is. Following one of my colleagues, at the end open source software 
grows under the premises of a virgin forest and some species survive and 
others die.

**Comment by rayosborn** [comment]
I think we've got to the point where it would be more fruitful to discuss this during the NIAC, although I don't want to stop people who are not here from continuing to comment.

**Comment by mkoennecke** [comment]
A NIAC decision was reached: A mask can be stored under the name DATASETNAME_mask wherever this is required. The conventions of NXdetector/pixel_mask apply for valid mask values. 
Accepted with 10/0/1
