### ISSUE TITLE
[NIAC 2018 Proposal] NXptycho definition

### ISSUE THREAD

**Issue by markbasham** [nexusformat/NIAC#36]

**Comment by mkoennecke** [comment]
Renamed to NXcxi and accepted by the NIAC with 7/3/0

**Comment by PeterC-DLS** [comment]
This refers to the [NXcxi_ptycho](https://github.com/nexusformat/definitions/blob/master/contributed_definitions/NXcxi_ptycho.nxdl.xml) contributed definition
