### ISSUE TITLE
NIAC 2018: NeXus as logbook format?

### ISSUE THREAD

**Issue by mkoennecke** [nexusformat/NIAC#37]
This is a suggestion to use NeXus for electronic logbooks. There are some advantages to this. This is 
a discussion topic to figure out if it is a good idea and in order to decide if we want to do down this road at all.

**Comment by vasole** [comment]
I think the conclusion was that while it could be used to store the information, it lacked the flexibility an actual electronic logbook provides (easily editable, searchable,...)

**Comment by mkoennecke** [comment]
The NIAC decided that this is a nice idea but outside of the scope of NeXus.
