### ISSUE TITLE
Code Camp 2020-2 topics

### ISSUE THREAD

**Issue by benajamin** [nexusformat/NIAC#38]
Anyone wanting to discuss issues at the 2020-2 NeXus Code Camp is asked to please add a comment here describing the topics they want to work on together with the core NeXus developers. We mostly want to be prepared for the number and types of issues being brought to us.

**Comment by prjemian** [comment]
1. NXDL release [*NXDL 2020.10*](https://github.com/nexusformat/definitions/milestone/9)
1.

**Comment by prjemian** [comment]
Also, I created a new `code camp` label in the definitions repo to mark issues for consideration at the next code camp.  Adding to my list above.

**Comment by mkoennecke** [comment]
I would like to work on cnxvalidate issues. We need to establish an order of importance though..

**Comment by prjemian** [comment]
Once issues for each of the above topics have been created, this issue can be closed.

**Comment by RussBerg** [comment]
I would like to get feedback from everyone on the nxdl_to_hdf5 stuff I have put together for **exampledata**, if it still needs work or if it can be merged (https://github.com/nexusformat/exampledata/pull/18)

**Comment by benajamin** [comment]
Event has concluded - issue no longer needed.
