### ISSUE TITLE
Discuss revision of existing classes to use 2014 attributes

### ISSUE THREAD

**Issue by zjttoefs** [nexusformat/NIAC#4]
Proposed changes are here:

https://github.com/nexusformat/definitions/issues/443

Do we want to got ahead with that?
Obviously versioning support would help.

**Comment by prjemian** [comment]
versioning support issue: https://github.com/nexusformat/definitions/issues/387

**Comment by prjemian** [comment]
Here is a page of the proposed work
https://github.com/nexusformat/definitions/compare/issue_447

find your pet NXDL and make changes based on the suggestions

**Comment by zjttoefs** [comment]
This should appear in the minutes and can then be closed. I would not say that that's material for the manual.

**Comment by prjemian** [comment]
per NIAC2018, closing this

should consider this issue when updating any application definition
