### ISSUE TITLE
test poll: the bikeshed color

### ISSUE THREAD

**Issue by prjemian** [nexusformat/NIAC#40]
Should we paint the bike shed?

/polls red green 'no color'

**Comment by prjemian** [comment]
https://github.com/apps/polls

**Comment by prjemian** [comment]
Follow from the example: https://github.com/evenchange4/gh-polls-bot

**Comment by PeterC-DLS** [comment]
Maybe this: https://github.com/marketplace/actions/github-polls-bot-action

**Comment by prjemian** [comment]
And another alternative (perhaps more bare-bones?): https://github.com/apex/gh-polls

I'll cancel the  https://github.com/evenchange4 poll, it must need something else that I'm missing from the docs.  .yml file, .env file, something.

**Comment by prjemian** [comment]
let me practice this in a different repo that does not spam everyone, we'll get this ...

**Comment by prjemian** [comment]
note taking: https://github.com/imjohnbo/gh-polls-bot-action

**Comment by prjemian** [comment]
I like the idea of https://github.com/marketplace/actions/github-polls-bot-action which associates a poll with a workflow.  We could identify an issue for NIAC consideration (as we have with a label) and that would create a poll, in theory, on which the NIAC could vote electronically.  We'd need to address the NIAC constitution to consider such votes but let's try this first.

**Comment by prjemian** [comment]
I've gone fishing for help on this one: https://stackoverflow.com/questions/62683421/how-to-install-user-feedback-polls-for-github-issues

**Comment by prjemian** [comment]
no help for this
