### ISSUE TITLE
NIAC 2020 topics

### ISSUE THREAD

**Issue by prjemian** [nexusformat/NIAC#42]
Anyone wanting to discuss issues at the 2020 NIAC meeting is asked to please add a comment here describing the topics they want brought before the NIAC. We mostly want to be prepared for the number and types of issues being brought to us.

**Comment by prjemian** [comment]
1. [Definitions Issues marked for NIAC review](https://github.com/nexusformat/definitions/issues?q=is%3Aopen+is%3Aissue+label%3A%22NIAC+should+review%22)
1. NXDL release [*NXDL 2020.10*](https://github.com/nexusformat/definitions/milestone/9)

**Comment by mkoennecke** [comment]
1. Naming conventions[]( https://github.com/nexusformat/definitions/pull/671)
2. NXdata changes[]( https://github.com/nexusformat/definitions/pull/602)
3. Reserved prefixes[]( https://github.com/nexusformat/definitions/issues/769)

**Comment by mkoennecke** [comment]
Cleanup of issues: triage into still relevant, minor (someone just edit this), to be discussed

**Comment by yayahjb** [comment]
Final vote on recently revised NXmx for Gold Standard being used by DECTRIS
for their FileWriter 2.   See Bernstein HJ, Förster A, Bhowmick A, Brewster AS, Brockhauser S, Gelisio L, Hall DR, Leonarski F, Mariani V, Santoni G, Vonrhein C. Gold Standard for macromolecular crystallography diffraction data. IUCrJ. 2020 Sep 1;7(5).

**Comment by rayosborn** [comment]
Future of Python in the NeXus API language bindings

**Comment by phyy-nx** [comment]
nexusformat/definitions#711, Math support in NeXus

**Comment by prjemian** [comment]
separate issues were created for all items above so can close now
