### ISSUE TITLE
[NIAC2020] Final vote on NXmx

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/NIAC#45]
Final vote on recently revised NXmx for Gold Standard being used by DECTRIS
for their FileWriter 2. See [Bernstein HJ, Förster A, Bhowmick A, Brewster AS, Brockhauser S, Gelisio L, Hall DR, Leonarski F, Mariani V, Santoni G, Vonrhein C. Gold Standard for macromolecular crystallography diffraction data. IUCrJ. 2020 Sep 1;7(5)](https://europepmc.org/article/pmc/pmc7467160).

proposed for discussion by @yayahjb

**Comment by yayahjb** [comment]
Also see http://www.medsbio.org/meetings/HDRMX_22Aug20_files/Gold_Standard_22Aug20_HJB.pdf

**Comment by prjemian** [comment]
Discussion included [suggested revisions for `NXdetector`, `NXdetector_group`, and `NXdetector_module` base classes](https://github.com/nexusformat/definitions/pull/802) in synchronization with the revised `NXmx` application definition.

**Comment by yayahjb** [comment]
After Aaron and Pete made their changes, I made a further attempt to align NXmx and NXdetector_group in PR 801 in defintions.  I think we have now addressed the issues that were raised for NXmx

**Comment by benajamin** [comment]
The proposal is to accept the NXmx application definition. All NIAC members are asked to cast their vote by attaching a thumbs up emoji to accept, a thumbs down to reject and any other emoji to abstain.

**Comment by benajamin** [comment]
The NXmx application definition is accepted with 13 votes in favour and 3 abstentions.
