### ISSUE TITLE
[NIAC2020] clarify naming conventions for fields etc.

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/NIAC#47]
See nexusformat/definitions#671 and  nexusformat/definitions#544 and ~~nexusformat/definitions#791~~

proposed for discussion by @mkoennecke

**Comment by benajamin** [comment]
There is agreement that some relaxation could be warranted, but the details of the exact regex should be discussed at the CodeCamp first.

**Comment by benajamin** [comment]
to be fixed by https://github.com/nexusformat/definitions/pull/671

**Comment by benajamin** [comment]
Proposal is described here: https://github.com/nexusformat/definitions/pull/671#issuecomment-715476138
Proposal was accepted with 13 votes in favour (0 against).
Implemented by https://github.com/nexusformat/definitions/pull/671
