### ISSUE TITLE
[NIAC2020] reserved prefixes for names

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/NIAC#49]
Discuss reserved prefixes for class, field and attributes

See nexusformat/definitions#769 and nexusformat/definitions#770

Proposed for discussion by @mkoennecke

**Comment by benajamin** [comment]
Proposal is to reserve the following prefixes:
prefix | use | meaning | URL
---- | ---- | ---- | ----
`NX` | NXDL class | For the class names used with NeXus groups | www.nexusformat.org
`NX_` | attributes | reserved for use by NeXus | www.nexusformat.org
`SAS_` | attributes | reserved for use by canSAS | (?URL?)
`SILX_` | attributes | reserved for use by silx | www.silx.org
`PDBX_` | attributes | reserved for the US protein data bank | www.rcsb.org


-    thumbs up to accept
-    thumbs down to reject
-    any other emoji to abstain

**Comment by benajamin** [comment]
Proposal is to allow the set of reserved prefixes to be managed by the technical committee (i.e. at teleconferences):
-    thumbs up to accept
-    thumbs down to reject
-    any other emoji to abstain

**Comment by prjemian** [comment]
The only *management* delegated to the technical committee is to **add** to the list.

**Comment by benajamin** [comment]
Proposal to reserve name prefixes is accepted with 14 votes in favour and 1 against.
Proposal to accept set of prefixes (see above) is accepted with 15 votes in favour and 1 against.
Proposal to allow the technical committee to add new prefixes is accepted with 14 votes in favour and 1 against.
Implemented via https://github.com/nexusformat/definitions/pull/808

Note that a further prefix was proposed and accepted in https://github.com/nexusformat/NIAC/issues/80
