### ISSUE TITLE
[NIAC2020] NXDL 2020.10 release

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/NIAC#50]
Review items in https://github.com/nexusformat/definitions/milestone/9

proposed for discussion by @prjemian

**Comment by benajamin** [comment]
This needs to be done at the CodeCamp, no general NIAC decision is required. This issue was opened here just as a news item.

**Comment by PeterC-DLS** [comment]
Release has happened: https://github.com/nexusformat/definitions/releases/tag/v2020.10

**Comment by prjemian** [comment]
Thanks to all the NeXus team, and especially @PeterC-DLS for finalizing!
