### ISSUE TITLE
[NIAC2020] Missing @creator_version in NXroot

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/NIAC#51]
See nexusformat/definitions#789

Issue originally raised by @vasole proposed for NIAC202 discussion by @prjemian

**Comment by benajamin** [comment]
Proposal is to accept the additional @creator_version in NXroot.

- thumbs up to accept
- thumbs down to reject
- any other emoji to abstain

**Comment by benajamin** [comment]
Proposal is accepted with 15 votes in favour and 1 abstention.
Implemented by https://github.com/nexusformat/definitions/pull/790
