### ISSUE TITLE
[NIAC2020] Review and Standardise symbol naming in NXDL

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/NIAC#52]
See for example nexusformat/definitions#786 and nexusformat/definitions#800

Proposed for discussion by @RussBerg

**Comment by benajamin** [comment]
This was discussed in session D and it was decided that the issue is a simple bug-fix that will not change the actual data format and so doesn't require NIAC approval.
Fixed by https://github.com/nexusformat/definitions/pull/819
