### ISSUE TITLE
NeXus Ptychography discussion on geometry

### ISSUE THREAD

**Issue by FreddieAkeroyd** [nexusformat/NIAC#53]
Proposed by @prjemian

**Comment by prjemian** [comment]
PJ mentioned that he has been approached regarding a NeXus ptychography format for reduced data and how best to describe e.g. beam centre x and y in NeXus. HB indicated that there are overlaps with NXmx and it would be good to have a common approach and terminology. It was agreed to discuss this at the NIAC/code camp. NIAC

**Comment by prjemian** [comment]
Nothing to vote on here, just make a recommendation.

**Comment by prjemian** [comment]
There is no consensus approach.

**Comment by prjemian** [comment]
Use NXtransformations to describe the position of the detector.  Is there an example to follow?

**Comment by phyy-nx** [comment]
Example from XFEL: https://doi.org/10.5281/zenodo.3352357

**Comment by prjemian** [comment]
see https://manual.nexusformat.org/design.html#coordinate-transformations

**Comment by yayahjb** [comment]
The equivalent beam center code for CBF using the CBF coordinate system in 
https://github.com/yayahjb/cbflib/blob/master/src/cbf_simple.c
in the routines cbf_get_pixel_coordinates, cbf_get_beam_center and related
routines. -- Herbert

**Comment by mkoennecke** [comment]
I found some slides from the original suggestion. This has been heavily modified since and we based our decision on what is on within now. 
[NXTransform.pdf](https://github.com/nexusformat/NIAC/files/5370438/NXTransform.pdf)
![rotcombi](https://user-images.githubusercontent.com/5029850/95844181-e2465a80-0d48-11eb-87f6-45d44ed4ccb3.png)

**Comment by prjemian** [comment]
Additional notes for the ptycho community about the `depends_on` chain are placed in https://github.com/nexusformat/definitions/issues/864#issuecomment-740689052.

Thanks for the contributions!
