### ISSUE TITLE
NXsas: review use of minOccurs on various components 

### ISSUE THREAD

**Issue by prjemian** [nexusformat/NIAC#58]
https://github.com/nexusformat/definitions/issues/522

**Comment by prjemian** [comment]
Not ready for NIAC consideration yet.

**Comment by prjemian** [comment]
There is no PR for this issue at this time.  The issue (in definitions repo) was posted 5 years ago.  It is possible that some community discussion needed to make a new PR ready.  I suggest we move this issue to the next NIAC meeting (later in 2022).

**Comment by prjemian** [comment]
Still no branch & PR

**Comment by benajamin** [comment]
Proposal is to accept the changes to NXsas in pull request https://github.com/nexusformat/definitions/pull/1194
