### ISSUE TITLE
Streaming NeXus

### ISSUE THREAD

**Issue by mkoennecke** [nexusformat/NIAC#6]
At more and more places data is streamed: i.e you get possibly multidimensional data with time stamps. 
Nexus ought to have a plan how to store this kind of data. Previous work include neutron event storage but we have two different versions of this. A more generalized version is needed.

**Comment by zjttoefs** [comment]
Mark to present his upcoming white paper

**Comment by mkoennecke** [comment]
I have attached a white paper on streaming, both in markdown and pdf format. Please have a look. I especially like someone with more experience with FELS to have a look and check if the recommended solution fits the FEL use case.
[NXStreaming.pdf](https://github.com/nexusformat/NIAC/files/426494/NXStreaming.pdf)
[NXStreaming.txt](https://github.com/nexusformat/NIAC/files/426495/NXStreaming.txt)

**Comment by mkoennecke** [comment]
I pushed the documents now into the NIAC repository, for editing
