### ISSUE TITLE
NXtofraw explains azimuthal_angle as "polar angle"

### ISSUE THREAD

**Issue by prjemian** [nexusformat/NIAC#62]
https://github.com/nexusformat/definitions/issues/325

**Comment by prjemian** [comment]
This is only a change of one word in the documentation.  Does not need NIAC discussion or approval.  WIll close once definitions pull request is merged.

**Comment by benajamin** [comment]
This is a simple documentation bug and is corrected by https://github.com/nexusformat/definitions/pull/988
