### ISSUE TITLE
propose to ratify NXcanSAS as application definition

### ISSUE THREAD

**Issue by prjemian** [nexusformat/NIAC#7]
http://download.nexusformat.org/doc/html/classes/contributed_definitions/NXcanSAS.html#nxcansas

see issue https://github.com/nexusformat/definitions/issues/420

* current HTML documentation snapshot: https://github.com/nexusformat/NIAC/blob/master/2016/NXcanSAS.pdf
* structure: https://github.com/canSAS-org/NXcanSAS_examples/blob/master/resources/NXcanSAS_outline.txt
* example data files: https://github.com/canSAS-org/NXcanSAS_examples/tree/master/1d_standard
* structure of one of these files: https://github.com/canSAS-org/NXcanSAS_examples/blob/master/1d_standard/structure/cs_collagen.h5.txt

**Comment by zjttoefs** [comment]
Pete, are you willing and able to present that at the NIAC?

**Comment by prjemian** [comment]
Yes, but I will have to do that by telepresence since I cannot travel.

**Comment by prjemian** [comment]
superceded by #8

**Comment by prjemian** [comment]
Looks ready to go.  The remaining tasks in #420 are to update the graphics and make an example data file from APS. These are not necessary for the review to proceed.

**Comment by prjemian** [comment]
Note that several 1-D example data files are from APS SAXS instruments.  Thus, only the "graphics to be updated" item remains from #420.

**Comment by prjemian** [comment]
NXinstrument should be an optional group since it is not a requirement for all SAS analysis

Other groups should be declared optional that are not part of the minimal standard as proposed by canSAS2012 in Uppsala.

With these provisions, the NXcanSAS was ratified.

canSAS should review this work.  If further revision is desired, then the version number of the standard will be advanced with those changes.

**Comment by prjemian** [comment]
see associated pull request: https://github.com/nexusformat/definitions/issues/492
