### ISSUE TITLE
Elect Officers

### ISSUE THREAD

**Issue by benajamin** [nexusformat/NIAC#70]
We need to elect new officers for the NIAC. Freddie Akeroyd and Benjamin Watts have been nominated from those attending the NIAC session. Please vote or nominate another candidate. The voting will remain open until the final NIAC2020 session, which is to be at a date yet to be decided (after the CodeCamp2020-2 : Oct 19-20).

There have been strong arguments that having both a Definitions and Technical Manager is unwarranted (especially with the NAPI not being actively developed anymore). We may consider amending the constitution at the 2022 NIAC to merge these two offices. For now, we might just elect a single person for both roles.

**Comment by benajamin** [comment]
Proposal is to elect Freddie Ackeroyd as NIAC secretary.
- thumbs up to accept
- thumbs down to reject
- any other emoji to abstain

**Comment by benajamin** [comment]
Proposal is to elect Benjamin Watts as NIAC Chair.
- thumbs up to accept
- thumbs down to reject
- any other emoji to abstain

**Comment by benajamin** [comment]
Proposal is to elect Peter Chang as Documentation Release Manager.
- thumbs up to accept
- thumbs down to reject
- any other emoji to abstain

**Comment by benajamin** [comment]
Proposal is to elect Peter Chang as Technical Manager.
- thumbs up to accept
- thumbs down to reject
- any other emoji to abstain

**Comment by benajamin** [comment]
I nominate Stuart Campbell for Technical Manager.
Stuart: Do you accept the nomination?

**Comment by stuartcampbell** [comment]
> I nominate Stuart Campbell for Technical Manager.
> @stuartcampbell : Do you accept the nomination?

I would yes, but looks like @PeterC-DLS has already got a lot of votes for this position.

**Comment by benajamin** [comment]
Proposal is to elect Stuart Campbell as Technical Manager.
-    thumbs up to accept
-    thumbs down to reject
-    any other emoji to abstain

**Comment by benajamin** [comment]
The elected NIAC officers are:
Office | Name | Votes (for/against/abstain)
-- | -- | --
Chair | Benjamin Watts | (14/1/0)
Secretary | Freddie Akeroyd | (12/0/1)
Release Manager | Peter Chang | (12/0/1)
Technical Release Manager | Stuart Campbell | (12/0/2)
