### ISSUE TITLE
Changes to constitution

### ISSUE THREAD

**Issue by benajamin** [nexusformat/NIAC#71]
Changes to the constitution were voted on at NIAC2018

**Comment by benajamin** [comment]
We direct the technical committe to publish the changes to the consititution that were voted on in 2018.

**Comment by prjemian** [comment]
NIAC2018 minutes: https://www.nexusformat.org/NIAC2018Minutes.html

Changes were:

* Voting

> Email voting as used up to 2018 only for membership renewals
> 
> For issues other than membership renewals, the following rule applies: we vote by teleconference where the proposal can be discussed. At least 2/3 of the NIAC have to be present at the teleconference. Then normal majority vote of the attendees applies. Teleconference decisions need to be published on the NIAC mailing list. NIAC Members not attending the teleconference have a one week period in which they can add their vote to the tally. Those not responding in that week are counted as abstained.

**Comment by prjemian** [comment]
Just the second paragraph to be added?

Any other changes?

**Comment by prjemian** [comment]
NOTE: this is the file to edit: https://github.com/nexusformat/wiki/blob/master/content/NIAC.md#constitution

**Comment by prjemian** [comment]
see PR https://github.com/nexusformat/wiki/pull/6

**Comment by benajamin** [comment]
@benajamin and @yayahjb to try rewriting the text and will bring it back soon.

**Comment by prjemian** [comment]
See this discussion for how to vote on GitHub: https://github.com/nexusformat/definitions/issues/795

**Comment by benajamin** [comment]
In 2018, we voted for new rules regarding voting ([minutes](https://www.nexusformat.org/NIAC2018Minutes.html#decision_voting)). When adding the new text to the [constitution](https://www.nexusformat.org/NIAC.html), we noticed that it wasn't very clear and lacked the context of the discussion just before the vote that the new rules concern voting outside of the biennial NIAC meetings. We worked on a more suitable text during the code camp - the quoted text below is the entire section on voting, with new text in bold.

> Voting: Only members of the NeXus International Advisory Committee will be able to vote on specific proposals that come under the remit of the committee. However, all debates will be conducted publicly and non-committee members are both allowed and encouraged to participate.
>
> Topics voted on **at the biennial NIAC meetings** will require a simple majority unless specifically
> challenged by a committee member. In the event of a challenge, the issue
> will be presented to the NeXus mailing list inviting comments for a
> period of one month. At the end of this period, the challenge can be
> overruled by a two thirds majority.
> 
> **Voting outside of the biennial NIAC meetings can take two forms. 
> Firstly, memberships can be approved by email ballot. All other issues
> require a teleconference for interactive discussion that is attended by 
> at least 2/3 of the NIAC. Votes may be cast at the teleconference, as well
> as during the following week in order to allow NIAC members not attending
> the teleconference to add their vote to the tally. The opening of the 
> voting period must be advertised through the NIAC mailing list. At the 
> close of the 1-week voting period, NIAC members not responding are counted
> as abstained and the NIAC decision follows the voting category (usually
> "for" and "against") with the highest number of valid votes.**
> 
> The constitution can only be changed by a two thirds majority of the NIAC.

 The NIAC should consider the text and possible further changes. A NIAC vote is required to accept the new constitution.

**Comment by benajamin** [comment]
Proposal is to accept the above text into the NIAC constitution.

- thumbs up to accept
- thumbs down to reject
- any other emoji to abstain

**Comment by prjemian** [comment]
This needs further discussion to retire various objections to what constitutes quorum, what constitutes majority, what constitutes a NIAC meeting.

**Comment by FreddieAkeroyd** [comment]
Could the 2/3 quorum for TC be changed to 50% at a later point by just an email vote of the NIAC, or needs a full NIAC?

**Comment by benajamin** [comment]
@FreddieAkeroyd 
The current rules state that a teleconference with 2/3 attendance is required for any non-membership NIAC vote that occurs outside of the biennial meeting. Further, changes to the voting rules require a constitution change, which also requires a 2/3 quorum. The rules can be changed if these criteria are met. This should be possible, but it is not an "email vote" as your question suggests.

**Comment by benajamin** [comment]
Proposal is accepted with 15 votes for and 0 against.
Implemented by https://github.com/nexusformat/wiki/pull/8
