### ISSUE TITLE
[NXdata] Inconsistency in documentation?

### ISSUE THREAD

**Issue by vasole** [nexusformat/NIAC#76]
In rules, 
https://manual.nexusformat.org/rules.html?highlight=axes

the ``@axes`` attribute is presented as a single string with spaces separating each axis:

![image](https://user-images.githubusercontent.com/5636251/96840617-fbd35a80-144a-11eb-8137-2b55452156fe.png)

![image](https://user-images.githubusercontent.com/5636251/96840367-a1d29500-144a-11eb-8929-27ea1a7b6569.png)

That is in discrepancy with the correct form detailed under NXdata

![image](https://user-images.githubusercontent.com/5636251/96840463-c75f9e80-144a-11eb-96e2-8e1a5b7f37d2.png)

**Comment by vasole** [comment]
The confusion might come from the old information:

https://manual.nexusformat.org/nxdl_desc.html?highlight=interpretation#axes

where one can find:

![image](https://user-images.githubusercontent.com/5636251/96841407-10fcb900-144c-11eb-9544-25978c5ea0e9.png)

However, the separation by spaces doe snot seem to be considered anywhere

**Comment by benajamin** [comment]
I think this is related to the images in the manual being out of date as discussed in https://github.com/nexusformat/definitions/issues/474. This is something that needs somebody to do the _work_ of making new graphics (preferably with a script to allow later updates) rather than a NIAC decision.

**Comment by prjemian** [comment]
While the graphics are out of date, that's not the problem reported here.  (Update of the graphics is a target for a future code camp.)  This is a consistency issue between content in `manual/source/rules.rst`, `base_classes/NXdata.nxdl.xml`, and `nxdl.xsd`.

* `rules.rst` uses:

  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/manual/source/examples/hierarchy-processed.txt#L11
  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/manual/source/examples/hierarchy-raw.txt#L12

* NXdata

  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/base_classes/NXdata.nxdl.xml#L99
  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/base_classes/NXdata.nxdl.xml#L138

* nxdl.xsd

  - The [comment cited above](https://github.com/nexusformat/NIAC/issues/76#issuecomment-714304106) applies to the `axes` attribute of a *field*.  The documentation should be clarified to this distinction.
  - https://github.com/nexusformat/definitions/blob/1afe941a1e9d95522619e971ac23464b2b610675/nxdl.xsd#L688-L707

I will resolve all of these references to be consistent with _with the actual layout in the file as it is described in NXdata_.  Agree?

**Comment by vasole** [comment]
@prjemian I agree with your interpretation (NXdata is the layout to be considered correct)

**Comment by prjemian** [comment]
See PR https://github.com/nexusformat/definitions/pull/853 for proposed changes.

**Comment by benajamin** [comment]
https://github.com/nexusformat/definitions/pull/853 is merged and this looks to be resolved.
