### ISSUE TITLE
Addition of globally unique identifier to NXentry (and potentially others)

### ISSUE THREAD

**Issue by stuartcampbell** [nexusformat/NIAC#80]
The current `NXentry` has the field `entry_identifier` which is defined as a "unique identifier for the measurement, defined by the facility."

Facilities that are using the [Bluesky data acquisition](https://blueskyproject.io) have both a unique identifier (which is a uuid) and a 'transient identifier' which is along the lines of a traditional scan/run identifier. 

As more facilities are adopting Bluesky, it would be nice to come to a recommendation on how to store both the `uuid` and scan id before we all develop our own standards.   At the moment, I can see an argument for storing either the 'scan id' or the 'uuid' in the `entry_identifier` - but then where to store the other one.

Either adding an optional field like `entry_uuid` or `unique_entry_identifier` or allowing the adding a `uuid` attribute ?

**Comment by stuartcampbell** [comment]
Actually, based on the previous discussion on the `beam_size_x` type issue, I would propose either `entry_uuid` or `entry_identifier_uuid` seem to fit with the recommendations.

**Comment by prjemian** [comment]
NeXus allows the addition of field not defined in the NXDL base class.  This proposal is to identify and reserve the names of specific fields for two terms that are part of Bluesky.  Such inclusion in the NeXus base class will standardize how NeXus files are generated from Bluesky data (and the reverse as well).

Citing from the manual about the [NeXus Community](https://manual.nexusformat.org/community.html#nexus-community):

> NeXus began as a group of scientists with the goal of defining a common data storage format to exchange experimental results and to exchange ideas about how to analyze them.

Already, NeXus is proposed as an interchange format to **exchange** Bluesky data with high-performance computing and machine learning.

**Comment by prjemian** [comment]
What is the bluesky entity identified by `entry_identifier_uuid`?

**Comment by prjemian** [comment]
Examples of current use (not necessarily consistent with this proposal) are here:  https://apstools.readthedocs.io/en/latest/source/_filewriters.html?highlight=NeXus#hdf5-nexus-file-structures

**Comment by prjemian** [comment]
uuid4: https://docs.python.org/3/library/uuid.html#uuid.uuid4

**Comment by stuartcampbell** [comment]
> What is the bluesky entity identified by `entry_identifier_uuid`?

The start  document uid

**Comment by stuartcampbell** [comment]
Proposal:  
- To add `entry_identifier_uuid` as an optional field on the `NXentry`

**Comment by prjemian** [comment]
DOI for UUIDs: https://doi.org/10.17487%2FRFC4122

**Comment by benajamin** [comment]
The proposal was accepted with 13 votes for (0 against)
@stuartcampbell has said that the Bluesky project prefix should be `BLUESKY_`

**Comment by prjemian** [comment]
UUID specification: https://www.rfc-editor.org/rfc/rfc4122.html
