### ISSUE TITLE
Code Camp 2021-1 topics

### ISSUE THREAD

**Issue by benajamin** [nexusformat/NIAC#82]
Anyone wanting to discuss issues at the 2021-1 NeXus Code Camp is asked to please add a comment here describing the topics they want to work on together with the core NeXus developers. If possible, link to a Github issue (in the appropriate repository) that describes the specific details.

**Comment by RussBerg** [comment]
on the october call I mentioned that I have adapted the nxdl_to_hdf5.py code to generate h5py based examples for all of the generated application definition hdf5 files, I wouldn't mind discussing this further to see if others feel there is value in including the h5py based generated examples and if so also I could work on creating nexpy versions of the generated examples as well.

**Comment by PeterC-DLS** [comment]
Discuss improving the documentation in https://github.com/nexusformat/definitions/issues/885

**Comment by mkoennecke** [comment]
Explicitly add depends_on and shape fields to all component type classes? #681

**Comment by benajamin** [comment]
I would like to work further on adding the [Python code examples](https://github.com/nexusformat/definitions/issues/807) to the documentation. Should we start by considering the [Sphinx extension for code tabs](https://github.com/nexusformat/definitions/issues/854)?
