### ISSUE TITLE
Documentation review - discussions

### ISSUE THREAD

**Issue by hgoerzig** [nexusformat/NIAC#83]
Review existing documentation considering understandability for newbies. Related to issue: https://github.com/nexusformat/definitions/issues/886

**Comment by BalazsBago** [comment]
Dear Heike,

This is what I have so far:

https://manual.nexusformat.org/introduction.html
Explanation of “Links” uses constructs (NXdata, NXmonitor…) which are undefined at this point of the documentation. The definitions in the design chapter (https://manual.nexusformat.org/design.html#nexus-objects-and-terms) seems clearer than these definitions in the introduction.

https://manual.nexusformat.org/design.html
The explanations are missing for the “data type” (NX_NUMBER, NX_FLOAT, etc …) in parentheses at fields and attributes. 

Do We have some strategy for partitioning the documentation, or all of us are going to read the whole documentation?

Cheers,
Balazs

**Comment by BalazsBago** [comment]
I have created issues for my remarks:
https://github.com/nexusformat/NIAC/issues/85
https://github.com/nexusformat/NIAC/issues/86
https://github.com/nexusformat/NIAC/issues/87

**Comment by prjemian** [comment]
Individual issues are created so this issue is done.  @hgoerzig @BalazsBago Thanks!
