### ISSUE TITLE
Improve structure of examples chapter

### ISSUE THREAD

**Issue by BalazsBago** [nexusformat/NIAC#92]
https://manual.nexusformat.org/examples/index.html#examples-of-writing-and-reading-nexus-data-files

The 2.2.1. section is separated by languages and this is very helpful for newcomers like me, but the next section hides this serpatation under a link.
 
As a newbie I would like to find on this page a package and examples in my preferred language to write or/ read NeXus data and with the current structure it is not clear what shall I choose.

**Comment by benajamin** [comment]
moved to definitions repository
