### ISSUE TITLE
Is this answer in the documentation? "Hierarchy in NeXus application definitions? #874"

### ISSUE THREAD

**Issue by hgoerzig** [nexusformat/NIAC#93]
https://github.com/nexusformat/definitions/issues/874

Application definitions are explained here:
https://manual.nexusformat.org/classes/index.html
and
https://manual.nexusformat.org/applying-nexus.html#nxdl-tutorial-usingnxdl

But I could not find that they are interlinked.

**Comment by benajamin** [comment]
@yayahjb brought up at the recent telco that there are [different types of inheritance](https://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)#Types) and that we should discuss/decide which one should be used in NeXus.
