### ISSUE TITLE
NXmx total_flux

### ISSUE THREAD

**Issue by benajamin** [nexusformat/NIAC#96]
Analysis of experimental data often call for an estimate of the probe beam strength, but there are different measures possible. NXmx wants to be able to [require one of these](https://github.com/nexusformat/definitions/issues/986) and requests guidance on how it should be stated in the NXDL.

**Comment by woutdenolf** [comment]
PR to add different flux related fields to NXmx: https://github.com/nexusformat/definitions/pull/1082

**Comment by benajamin** [comment]
XML has a [choice element](https://www.w3schools.com/xml/el_choice.asp) that requires exactly one object from a set being present.

**Comment by benajamin** [comment]
This issue is basically the overlap of #1002 and #1082. Perhaps that makes it a duplicate?
